# Generated by Django 3.1.3 on 2023-05-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
